server:
  servlet:
    port: 8000
    contextPath: /api

spring:
  application:
    name: reddit-api

  datasource:
    url: jdbc:postgresql://localhost:3200/reddit
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        temp:
          user_jdbc_metadata_default: false

        jdbc:
          lob:
            non_contextual_creation=true:database-platform: org.hibernate.dialect.PostgreSQL9Dialect
